language: go

go:
  - 1.7

install:
  - go get -u github.com/whyrusleeping/gx
  - go get -u github.com/whyrusleeping/gx-go
  - go get -u -d github.com/ipfs/go-ipfs 2> /dev/null
  - cd $GOPATH/src/github.com/ipfs/go-ipfs
  - gx install
  - go install ./cmd/ipfs
  - make install
  - cd $TRAVIS_BUILD_DIR
  - go get

before_script:
  - go get -u github.com/golang/lint/golint

script:
  - golint

git:
  depth: 1 # speed up git clone