language: go

go:
  - 1.8

before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo pip install scikit-learn pyinstaller

install:
  - go get -u github.com/whyrusleeping/gx
  - go get -u github.com/whyrusleeping/gx-go
  - go get -u -d github.com/ipfs/go-ipfs
  - cd $GOPATH/src/github.com/ipfs/go-ipfs
  - make install
  - cd $TRAVIS_BUILD_DIR
  - gx install
  - go get
  - ./travis_install.sh

before_script:
  - go get -u github.com/golang/lint/golint
  - go get github.com/GeertJohan/fgt

script:
  - golint
  - ./run_tests.sh
    
git:
  depth: 1 # speed up git clone

sudo: required

virtualenv:
  system_site_packages: true